---
# tasks file for DB
- name: install mariadb
  yum:
    name: mariadb-server
    state: present

- name: MariaDB service start
  service:
    name: mariadb
    state: started
    enabled: yes

- name: install pip package maneger
  yum:
    name: pip
    state: present

- pip:
    name: pymysql

- name: mysql add user and password
  mysql_user:
    name: gyana
    password: 12345
    priv: '*.*:ALL'
    state: present

- name: mysql add root user and password
  mysql_user:
    name: root
    password: root
    host: localhost
    priv: '*.*:ALL'
    state: present

- name: Configure MariaDB to listen on all interfaces
  lineinfile:
    dest: /etc/my.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    state: present

- name: install httpd
  yum:
    name: httpd
    state: present

- name: start httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: install php
  shell:
    cmd: amazon-linux-extras install php8.2 -y

- name: install pHp MyAdmin
  get_url:
    url: https://files.phpmyadmin.net/phpMyAdmin/5.2.1/phpMyAdmin-5.2.1-english.zip
    dest: /var/www/html

- name: unzip phpMyAdmin
  shell:
    chdir: /var/www/html
    cmd: unzip phpMyAdmin-5.2.1-english.zip

- name: Rename File phpMyAdmin
  shell:
    chdir: /var/www/html
    cmd: mv -f phpMyAdmin-5.2.1-english phpMyAdmin

- name: Remove the zip file
  shell:
    chdir: /var/www/html
    cmd: rm -fr phpMyAdmin-5.2.1-english.zip

- name: restart httpd
  service:
    name: httpd
    state: restarted
